services:
  - type: web
    name: my-backend
    env: node
    plan: free
    branch: main
    rootDir: Server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: my-frontend
    env: node
    plan: free
    branch: main
    rootDir: Client
    buildCommand: npm install
    startCommand: npm run build && npm install -g serve && serve -s build
    envVars:
      - key: NODE_ENV
        value: production
